/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package pw.cdmi.box.app.convertservice.domain;

import java.sql.Timestamp;

import org.apache.commons.lang.builder.ToStringBuilder;

public class ImgObject 
{
	private String sourceObjectId;
	private String accountId;
	private String imageObjectId;
	private int totalPages;
	private String pageIndex;
	private int resourceGroupId;
	private Timestamp convertTime;

	public String getSourceObjectId()
	{
		return sourceObjectId;
	}

	public void setSourceObjectId(String sourceObjectId)
	{
		this.sourceObjectId = sourceObjectId;
	}

	public String getAccountId()
	{
		return accountId;
	}

	public void setAccountId(String accountId)
	{
		this.accountId = accountId;
	}

	public String getImageObjectId()
	{
		return imageObjectId;
	}

	public void setImageObjectId(String imageObjectId)
	{
		this.imageObjectId = imageObjectId;
	}

	public int getTotalPages()
	{
		return totalPages;
	}

	public void setTotalPages(int totalPages)
	{
		this.totalPages = totalPages;
	}

	

	public int getResourceGroupId()
	{
		return resourceGroupId;
	}

	public void setResourceGroupId(int resourceGroupId)
	{
		this.resourceGroupId = resourceGroupId;
	}

	public String getPageIndex()
	{
		return pageIndex;
	}

	public void setPageIndex(String pageIndex)
	{
		this.pageIndex = pageIndex;
	}

	public Timestamp getConvertTime()
	{
		return convertTime;
	}

	public void setConvertTime(Timestamp convertTime)
	{
		this.convertTime = convertTime;
	}

	@Override
	public String toString() {
		return ToStringBuilder.reflectionToString(this);
	}

	
}

