#ifndef _ONEBOX_NOTIFY_MSG_H_
#define _ONEBOX_NOTIFY_MSG_H_

#define NOTIFY_MSG_TYPE_MSG_START 150

#define NOTIFY_MSG_INFO_MOUNT_FAILED 150
#define NOTIFY_MSG_INFO_UNMOUNT_FAILED 151
#define NOTIFY_MSG_INFO_REG_LANA_FAILED 152
#define NOTIFY_MSG_INFO_PATH_TOO_LONG 153
#define NOTIFY_MSG_INFO_SAME_OBJECT_EXIST 154
#define NOTIFY_MSG_INFO_NS_ZERO_FILE 155 // not surpport zero byte file
#define NOTIFY_MSG_INFO_NS_LINK_FILE 156 // not surpport link file
#define NOTIFY_MSG_INFO_NS_HIDE_FILE 157 // not surpport hide file
#define NOTIFY_MSG_INFO_NS_MTD_NAME 158 // not surpport metadata extension filename
#define NOTIFY_MSG_INFO_FILE_IS_TRANS 159 // file is transfering
#define NOTIFY_MSG_INFO_NOT_SUPPORT 160

#define NOTIFY_MSG_TRANS_TASK_INSERT 200
#define NOTIFY_MSG_TRANS_TASK_DELETE 201
#define NOTIFY_MSG_TRANS_TASK_UPDATE 202
#define NOTIFY_MSG_MENU_SHARE_LINK 210
#define NOTIFY_MSG_MENU_SHARE 211
#define NOTIFY_MSG_MENU_LISTREMOTEDIR 212
#define NOTIFY_MSG_CHANGE_WORK_MODE 213
#define NOTIFY_MSG_SPEED 214
#define NOTIFY_MSG_DIFF_CNT 215
#define NOTIFY_MSG_CNT_LIMIT 216
//#define NOTIFY_MSG_REFRESH_ICON 217
#define NOTIFY_MSG_SCAN 218
#define NOTIFY_MSG_ERROR_CHANGED 219
#define NOTIFY_MSG_ROOT_CHANGE 220
#define NOTIFY_MSG_SHOW_TRANSTASKS 221

#define NOTIFY_MSG_FS_CREATE_FILE 100
#define NOTIFY_MSG_FS_CREATE_DIR 101
#define NOTIFY_MSG_FS_RENAME_FILE 102
#define NOTIFY_MSG_FS_RENAME_DIR 103
#define NOTIFY_MSG_FS_DELETE_FILE 104
#define NOTIFY_MSG_FS_DELETE_DIR 105
#define NOTIFY_MSG_FS_MOVE_FILE 106
#define NOTIFY_MSG_FS_MOVE_DIR 107
#define NOTIFY_MSG_FS_COPY_FILE 108
#define NOTIFY_MSG_FS_GET_LIST 109
#define NOTIFY_MSG_FS_GET_SPACE 110
#define NOTIFY_MSG_FS_GET_FILE_ATTR 111 // get file attributes
#define NOTIFY_MSG_FS_SET_FILE_ATTR 112 // set file attrubutes
#define NOTIFY_MSG_FS_FILE_UPLOAD 113
#define NOTIFY_MSG_FS_DIR_UPLOAD 114
#define NOTIFY_MSG_FS_FILE_DOWNLOAD 115
#define NOTIFY_MSG_FS_DIR_DOWNLOAD 116
#define NOTIFY_MSG_FS_FILE_CHANGE 117
#define NOTIFY_MSG_FS_DIR_CHANGE 118

#endif
