/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "OneboxThriftService_constants.h"

namespace OneboxThriftService {

const OneboxThriftServiceConstants g_OneboxThriftService_constants;

OneboxThriftServiceConstants::OneboxThriftServiceConstants() {
}

} // namespace

