/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef OneboxThriftService_CONSTANTS_H
#define OneboxThriftService_CONSTANTS_H

#include "OneboxThriftService_types.h"

namespace OneboxThriftService {

class OneboxThriftServiceConstants {
 public:
  OneboxThriftServiceConstants();

};

extern const OneboxThriftServiceConstants g_OneboxThriftService_constants;

} // namespace

#endif
