/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "OneboxSyncService_constants.h"

namespace Onebox { namespace SyncService {

const OneboxSyncServiceConstants g_OneboxSyncService_constants;

OneboxSyncServiceConstants::OneboxSyncServiceConstants() {
}

}} // namespace

