/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef OneboxSyncService_CONSTANTS_H
#define OneboxSyncService_CONSTANTS_H

#include "OneboxSyncService_types.h"

namespace Onebox { namespace SyncService {

class OneboxSyncServiceConstants {
 public:
  OneboxSyncServiceConstants();

};

extern const OneboxSyncServiceConstants g_OneboxSyncService_constants;

}} // namespace

#endif
