#ifndef _NOTIFY_MSG_H_
#define _NOTIFY_MSG_H_

#define NOTIFY_MSG_FS_CREATE_FILE 100
#define NOTIFY_MSG_FS_CREATE_DIR 101
#define NOTIFY_MSG_FS_RENAME_FILE 102
#define NOTIFY_MSG_FS_RENAME_DIR 103
#define NOTIFY_MSG_FS_DELETE_FILE 104
#define NOTIFY_MSG_FS_DELETE_DIR 105
#define NOTIFY_MSG_FS_MOVE_FILE 106
#define NOTIFY_MSG_FS_MOVE_DIR 107
#define NOTIFY_MSG_FS_COPY_FILE 108
#define NOTIFY_MSG_FS_GET_LIST 109
#define NOTIFY_MSG_FS_GET_SPACE 110
#define NOTIFY_MSG_FS_GET_FILE_ATTR 111 // get file attributes
#define NOTIFY_MSG_FS_SET_FILE_ATTR 112 // set file attrubutes
#define NOTIFY_MSG_FS_FILE_UPLOAD 113
#define NOTIFY_MSG_FS_DIR_UPLOAD 114
#define NOTIFY_MSG_FS_FILE_DOWNLOAD 115
#define NOTIFY_MSG_FS_DIR_DOWNLOAD 116
#define NOTIFY_MSG_FS_FILE_CHANGE 117
#define NOTIFY_MSG_FS_DIR_CHANGE 118

#define NOTIFY_MSG_TRANS_TASK_INSERT 200
#define NOTIFY_MSG_TRANS_TASK_DELETE 201
#define NOTIFY_MSG_TRANS_TASK_UPDATE 202
#define NOTIFY_MSG_TRANS_TASK_CANCEL 203
#define NOTIFY_MSG_TRANS_TASK_ERROR 204
#define NOTIFY_MSG_TRANS_TASK_COMPLETE 205
#define NOTIFY_MSG_TRANS_SPEED 206
#define NOTIFY_MSG_TRANS_TASK_REFRESH_UI 207
#define NOTIFY_MSG_TRANS_TASK_UPDATE_SIZE 208
#define NOTIFY_MSG_TRANS_TASK_UPDATE_NUMBER 2071

//#define NOTIFY_MSG_MENU_CREATEBACKUP 209
#define NOTIFY_MSG_MENU_SHARE_LINK 210
#define NOTIFY_MSG_MENU_SHARE 211
#define NOTIFY_MSG_MENU_LISTREMOTEDIR 212
#define NOTIFY_MSG_CHANGE_WORK_MODE 213
#define NOTIFY_MSG_SPEED 214
#define NOTIFY_MSG_DIFF_CNT 215
#define NOTIFY_MSG_CNT_LIMIT 216
//#define NOTIFY_MSG_REFRESH_ICON 217
#define NOTIFY_MSG_SCAN 218
#define NOTIFY_MSG_ERROR_CHANGED 219
#define NOTIFY_MSG_ROOT_CHANGE 220
#define NOTIFY_MSG_SHOW_TRANSTASKS 221
#define NOTIFY_MSG_REFRESH_THUMB 222
#define NOTIFY_MSG_GOTO_MYFILE 223
#define NOTIFY_MSG_GOTO_MYFILE_FOR_NAME 2231
#define NOTIFY_MSG_GOTO_SHARE2ME 224
#define NOTIFY_MSG_GOTO_SHARE2ME_FOR_NAME 2241
#define NOTIFY_MSG_GOTO_TEAMSPACE 225
#define NOTIFY_MSG_GOTO_TEAMSPACE_FOR_NAME 2251

#define NOTIFY_MSG_RESTTASK_START 230
#define NOTIFY_MSG_RESTTASK_COMPLETE 231
#define NOTIFY_MSG_RESTTASK_ERROR 232

#define NOTIFY_MSG_BACKUP_TASK_PROCESS 240
#define NOTIFY_MSG_BACKUP_TASK_STATUS_CHANGE 241
#define NOTIFY_MSG_BACKUPALL_TASKINFO_CHANGE 242

#define NOTIFY_MSG_POWER_CHANGE 250

#define NOTIFY_MSG_NETWORK_WIRELESS_EXIST 260
#define NOTIFY_MSG_NETWORK_WIRELESS 261
#define NOTIFY_MSG_NETWORK_CHANGE 262

#define NOTIFY_MSG_MSG_CHANGE 300

#define NOTIFY_MSG_SETSHARE_FAILED 1000
#define NOTIFY_MSG_ADDFULLBACKUP_SUCCESSED 1001
#define NOTIFY_MSG_ADDFULLBACKUP_FAILED 1002

#define NOTIFY_MSG_START_PLAY_LEAD 1003

#endif
