export const DOCUMENT_HAND_OVER_LIST = "DOCUMENT_HAND_OVER_LIST";
export const AUTHORITY_HAND_OVER = "AUTHORITY_HAND_OVER";
// 文档移交列表
export const DOCUMENT_HAND_OVER_INNER_LIST = "DOCUMENT_HAND_OVER_INNER_LIST";
// 离职管理
export const DEPARTURE_MANAGEMENT = "DEPARTURE_MANAGEMENT";
// 权限移交列表
export const TEAMSPACES_SPACES = "TEAMSPACES_SPACES";
// 预览
export const FILE_PREVIEW = "FILE_PREVIEW";
