#pragma once

namespace OfficeAddinControl
{	
	struct ControlNames
	{
		static const wchar_t* OFFICEADDINPROGRESSFRAME_ITEM_PROGRESS;
		static const wchar_t* OFFICEADDINPROGRESSFRAME_LIST_PROGRESS;
		static const wchar_t* OFFICEADDINPROGRESSFRAME_PROGRESS_STAT;
		static const wchar_t* OFFICEADDINPROGRESSFRAME_PROGRESS_LAYOUT;
		static const wchar_t* OFFICEADDINPROGRESSFRAME_SUCCESS_LAYOUT;
		static const wchar_t* OFFICEADDINPROGRESSFRAME_ITEM_NOTICEAREA;		
		static const wchar_t* OFFICEADDINPROGRESSFRAME_ITEM_FAIL;
		static const wchar_t* OFFICEADDINPROGRESSFRAME_ITEM_INFO;
		static const wchar_t* OFFICEADDINPROGRESSFRAME_BUTTON_CLOSE;
		static const wchar_t* OFFICEADDINPROGRESSFRAME_ITEM_OPERATIONS;
		static const wchar_t* OFFICEADDINPROGRESSFRAME_BTN_CANCL;
		static const wchar_t* OFFICEADDINPROGRESSFRAME_ITEM_NAME;
	};
}