/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Onebox.ThriftClient
{
  /// <summary>
  /// Authen type
  /// </summary>
  public enum Authen_Type
  {
    Authen_Type_Normal = 0,
    Authen_Type_Domain = 1,
  }
}
