/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Onebox.ThriftClient
{
  /// <summary>
  /// File type
  /// </summary>
  public enum File_Type
  {
    File_Type_Dir = 0,
    File_Type_File = 1,
  }
}
