/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Onebox.ThriftClient
{
  /// <summary>
  /// overlay icon status
  /// </summary>
  public enum OverlayIcon_Status
  {
    OverlayIcon_Status_None = 0,
    OverlayIcon_Status_Synced = 1,
    OverlayIcon_Status_Syncing = 2,
    OverlayIcon_Status_NoActionDelete = 3,
    OverlayIcon_Status_Invalid = 4,
  }
}
