/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Onebox.ThriftClient
{
  /// <summary>
  /// service status
  /// </summary>
  public enum Service_Status
  {
    Service_Status_Online = 0,
    Service_Status_Offline = 1,
    Service_Status_Error = 2,
    Service_Status_Pause = 3,
    Service_Status_Uninitial = 4,
  }
}
