/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Onebox.ThriftClient
{
  /// <summary>
  /// share right
  /// </summary>
  public enum Share_Right
  {
    Share_Right_R = 0,
    Share_Right_RW = 1,
  }
}
